CLASSES=\
	jdbm.btree.BPage	\
	jdbm.btree.BTree	\
	jdbm.helper.ByteArrayComparator	\
	jdbm.helper.ByteArraySerializer	\
	jdbm.helper.CacheEvictionException	\
	jdbm.helper.CachePolicy	\
	jdbm.helper.CachePolicyListener	\
	jdbm.helper.Conversion	\
	jdbm.helper.DefaultSerializer	\
	jdbm.helper.FastIterator	\
	jdbm.helper.IntegerComparator	\
	jdbm.helper.IntegerSerializer	\
	jdbm.helper.IterationException	\
	jdbm.helper.LongComparator	\
	jdbm.helper.LongSerializer	\
	jdbm.helper.MRU	\
	jdbm.helper.ObjectBAComparator	\
	jdbm.helper.Serialization	\
	jdbm.helper.Serializer	\
	jdbm.helper.SoftCache	\
	jdbm.helper.StringComparator	\
	jdbm.helper.Tuple	\
	jdbm.helper.TupleBrowser	\
	jdbm.helper.WrappedRuntimeException	\
	jdbm.htree.HashBucket	\
	jdbm.htree.HashDirectory	\
	jdbm.htree.HashNode	\
	jdbm.htree.HTree	\
	jdbm.recman.BaseRecordManager	\
	jdbm.recman.BlockIo	\
	jdbm.recman.BlockView	\
	jdbm.recman.CacheRecordManager	\
	jdbm.recman.DataPage	\
	jdbm.recman.FileHeader	\
	jdbm.recman.FreeLogicalRowIdPage	\
	jdbm.recman.FreeLogicalRowIdPageManager	\
	jdbm.recman.FreePhysicalRowId	\
	jdbm.recman.FreePhysicalRowIdPage	\
	jdbm.recman.FreePhysicalRowIdPageManager	\
	jdbm.recman.Location	\
	jdbm.recman.LogicalRowIdManager	\
	jdbm.recman.Magic	\
	jdbm.recman.PageCursor	\
	jdbm.recman.PageHeader	\
	jdbm.recman.PageManager	\
	jdbm.recman.PhysicalRowId	\
	jdbm.recman.PhysicalRowIdManager	\
	jdbm.recman.Provider	\
	jdbm.recman.RecordCache	\
	jdbm.recman.RecordFile	\
	jdbm.recman.RecordHeader	\
	jdbm.recman.TransactionManager	\
	jdbm.recman.TranslationPage	\
	jdbm.RecordManager	\
	jdbm.RecordManagerFactory	\
	jdbm.RecordManagerOptions	\
	jdbm.RecordManagerProvider
